name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          echo "${{ secrets.GA_CONTENTS }}" > "public/${{ secrets.GA_FILENAME }}"
      - name: Deploy
        uses: AEnterprise/rsync-deploy@v1.0
        env:
          DEPLOY_KEY: ${{ secrets.RSYNC_SSH_KEY }}
          ARGS: "-r --delete-after --quiet"
          SERVER_PORT: ${{ secrets.RSYNC_SSH_PORT }}
          FOLDER: "./public/*"
          SERVER_IP: ${{ secrets.RSYNC_SSH_IP }}
          USERNAME: ${{ secrets.RSYNC_SSH_USERNAME }}
          SERVER_DESTINATION: ${{ secrets.RSYNC_SSH_PATH }}
